# Generated by Django 5.1.2 on 2024-11-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localactor',
            name='community_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localactor',
            name='community_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='localactor',
            name='actor_type',
            field=models.CharField(choices=[('P', 'Person'), ('S', 'Service'), ('C', 'Community')], default='P', max_length=1),
        ),
    ]
