# Generated by Django 5.1.2 on 2024-11-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0003_localactor_inbox_localactor_outbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='remoteactor',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='remoteactor',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remoteactor',
            name='linked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='localactor',
            name='actor_type',
            field=models.CharField(choices=[('P', 'Person'), ('S', 'Service'), ('C', 'Community'), ('G', 'Group')], default='P', max_length=1),
        ),
    ]
