# Generated by Django 5.1.2 on 2024-11-09 04:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitypub', '0004_remoteactor_allowed_remoteactor_blocked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localactor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localactor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
